# Generated by Django 4.2.30 on 2026-05-11 08:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RoadmapHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role_name', models.CharField(max_length=200)),
                ('current_skills', models.JSONField(default=list)),
                ('missing_skills', models.JSONField(default=list)),
                ('roadmap_data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Roadmap Histories',
                'ordering': ['-created_at'],
            },
        ),
    ]
