# Generated by Django 4.2.30 on 2026-05-11 08:59

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('resumes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role_name', models.CharField(max_length=200)),
                ('job_description', models.TextField(blank=True)),
                ('resume_text', models.TextField(blank=True)),
                ('ats_score', models.IntegerField(default=0)),
                ('skills_match_score', models.IntegerField(default=0)),
                ('keyword_score', models.IntegerField(default=0)),
                ('experience_score', models.IntegerField(default=0)),
                ('readability_score', models.IntegerField(default=0)),
                ('missing_skills', models.JSONField(default=list)),
                ('suggested_keywords', models.JSONField(default=list)),
                ('strengths', models.JSONField(default=list)),
                ('weaknesses', models.JSONField(default=list)),
                ('improvement_tips', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resume', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analysis_reports', to='resumes.resume')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
